name = "m4spider-app"
pages_build_output_dir = "dist"

compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "SPY_AI"
models = [
    "@cf/mistralai/mistral-small-3.1-24b-instruct",
    "@cf/openai/gpt-oss-120b",
    "@cf/stabilityai/stable-diffusion-xl-base-1.0",
    "@cf/stabilityai/stable-diffusion-xl-refiner-1.0",
    "@cf/web-search/seznam-supersearch"
]

# ----------------------
# KV NAMESPACES (using arrays)
# ----------------------

[[kv_namespaces]]
binding = "CHAT_KV"
id = "chatkv"

[[kv_namespaces]]
binding = "USAGE_KV"
id = "usagekv"

[[kv_namespaces]]
binding = "IMAGE_KV"
id = "imagekv"
