name = "m4spider-app"
pages_build_output_dir = "dist"

compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "SPY_AI"
models = [
  "@cf/mistralai/mistral-small-3.1-24b-instruct",
  "@cf/openai/gpt-oss-120b",
  "@cf/leonardo/lucid-origin",
  "@cf/stabilityai/stable-diffusion-xl-refiner-1.0",
  "@cf/web-search/seznam-supersearch"
]

[[kv_namespaces]]
binding = "CHAT_KV"
id = "eb2d69fd31ca4d89b04f2a694bc80501"

[[kv_namespaces]]
binding = "USAGE_KV"
id = "42c39aaa0c06448d9bd91778b4db1e65"

[[kv_namespaces]]
binding = "IMAGE_KV"
id = "190c52b0640040b7bdae6d2bbcacebfa"


